
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public stats.TbGuardStats TbGuardStats {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbGuardStats = new stats.TbGuardStats(loader("stats_tbguardstats"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbGuardStats.ResolveRef(this);
    }
}

}
